//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOATicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndirim
    {
        public int indirimID { get; set; }
        public Nullable<System.DateTime> baslangicTarih { get; set; }
        public Nullable<System.DateTime> bitisTarih { get; set; }
        public Nullable<int> indirimOrani { get; set; }
        public string indirimAdi { get; set; }
    }
}
