//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOATicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSiparis
    {
        public int siparisID { get; set; }
        public Nullable<int> musteriId { get; set; }
        public Nullable<int> urunId { get; set; }
        public Nullable<int> siparisAdet { get; set; }
        public Nullable<System.DateTime> siparisTarih { get; set; }
    
        public virtual tblMusteri tblMusteri { get; set; }
        public virtual tblUrunler tblUrunler { get; set; }
    }
}
