//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOATicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSepet
    {
        public int sepetID { get; set; }
        public Nullable<int> musteriID { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> adet { get; set; }
    
        public virtual tblUrunler tblUrunler { get; set; }
    }
}
