//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOATicaret.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrunler()
        {
            this.tblFavori = new HashSet<tblFavori>();
            this.tblSepet = new HashSet<tblSepet>();
            this.tblSiparis = new HashSet<tblSiparis>();
        }
    
        public int urunID { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string urunAdi { get; set; }
        public Nullable<int> urunDetayStok { get; set; }
        public Nullable<decimal> urunDetayFiyat { get; set; }
        public Nullable<System.DateTime> urunDetayTarih { get; set; }
        public string urunDetayResim { get; set; }
        public string urunAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFavori> tblFavori { get; set; }
        public virtual tblKategori tblKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSepet> tblSepet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSiparis> tblSiparis { get; set; }
    }
}
